apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yaml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: llm-ops-server
  name: llm-ops-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llm-ops-server
  template:
    metadata:
      labels:
        io.kompose.network/dp-llm-ops-default: "true"
        io.kompose.service: llm-ops-server
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_HOST
              value: clickhouse.dev.smartnews.com
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: llm-ops-secret
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: llm-ops-secret
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PROTOCOL
              value: "http"
            - name: CLICKHOUSE_DATABASE
              value: default
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: llm-ops-server-env
          image: llm-ops-server:latest
          name: llm-ops-server
