version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  supertokens:
    image: supertokens/supertokens-postgresql:5.0
    restart: always
    ports:
      - "3567:3567"
    environment:
      POSTGRES_CONNECTION_URI: postgres://postgres:postgres@postgres:5432/supertokens

  influxdb:
    image: bitnami/influxdb:2.7.1
    restart: always
    environment:
      INFLUXDB_ADMIN_USER_TOKEN: "token123"
      INFLUXDB_ADMIN_USER_PASSWORD: "influxdb-admin"
      INFLUXDB_USER: "admin"
      INFLUXDB_USER_PASSWORD: "influxdb-admin"
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/bitnami/influxdb

  pezzo-server:
    image: ghcr.io/pezzolabs/pezzo/server:latest
    restart: always
    env_file:
      - ./.env
      - ./apps/server/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/pezzo
      - SUPERTOKENS_CONNECTION_URI=http://supertokens:3567
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=token123
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl 'http://pezzo-server:3000/api/healthz'"]
      interval: 5s
      timeout: 5s
      retries: 3

  pezzo-console:
    image: ghcr.io/pezzolabs/pezzo/console:latest
    restart: always
    env_file:
      - ./.env
      - ./apps/console/.env
    ports:
      - "4200:8080"
    depends_on:
      pezzo-server:
        condition: service_healthy

volumes:
  postgres_data: ~
  influxdb_data: ~
