apiVersion: v1
data:
  CONSOLE_HOST: http://llm-ops-console:4200
  DATABASE_URL: postgres://postgres:postgres@llm-ops-prd-0.c6xrdianp1t4.ap-northeast-1.rds.amazonaws.com:5432/pezzo
  KAFKA_BROKERS: localhost:9092
  OPENSEARCH_URL: http://localhost:9200
  PINO_PRETTIFY: "true"
  REDIS_URL: redis://llm-ops-redis-stack-server:6379
  SUPERTOKENS_CONNECTION_URI: http://llm-ops-supertokens:3567
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: llm-ops-server-env
  name: llm-ops-server-env
