apiVersion: v1
data:
  NX_BASE_API_URL: http://llm-ops-server:3000
  NX_DEBUG_MODE: "true"
  NX_SUPERTOKENS_API_DOMAIN: http://llm-ops-server:3000
  NX_SUPERTOKENS_WEBSITE_DOMAIN: http://llm-ops-console:4200
#  NX_SUPERTOKENS_WEBSITE_DOMAIN: http://localhost:4200
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: llm-ops-console-env
  name: llm-ops-console-env
