name: Report a bug ðŸ›
description: Create a report to help us improve
labels: "bug"
body:
- type: textarea
  attributes:
    label: Report
    description: "What issue have you encountered?"
    placeholder: "A clear and concise description of what issue bug is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: What did you expect to happen?
    placeholder: What did you expect to happen?
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to reproduce the problem
    description: "How can we reproduce this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
  validations:
    required: false
- type: textarea
  attributes:
    label: Logs (if applicable)
    description: "Provide any logs, if applicable. This will help us identify the issue."
    value: |
      ```
      example
      ```
  validations:
    required: false
- type: input
  attributes:
    label: Pezzo version
    description: >
      What version of Pezzo are you using?
  validations:
    required: false
- type: dropdown
  attributes:
    label: How do you use Pezzo?
    description: Where 
    options:
    - Local Development Setup
    - Docker Compose
    - Kubernetes Deployment
    - Pezzo Cloud
  validations:
    required: false
