apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: llm-ops-local-kms
  name: llm-ops-local-kms
spec:
  ports:
    - protocol: TCP
      port: 9981
      targetPort: 9981
#    - name: 9981-tcp
#      port: 9981
#      targetPort: 9981
  selector:
    io.kompose.service: llm-ops-local-kms
