apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: llm-ops-supertokens
  name: llm-ops-supertokens
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: llm-ops-supertokens
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/dp-llm-ops-default: "true"
        io.kompose.service: llm-ops-supertokens
    spec:
      containers:
        - env:
            - name: POSTGRES_CONNECTION_URI
              value: postgres://postgres:postgres@postgres:5432/supertokens
          image: supertokens/supertokens-postgresql:5.0
          livenessProbe:
            exec:
              command:
                - |
                  bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: ::1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
#                  bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: llm-ops-supertokens
          ports:
            - containerPort: 3567
              hostPort: 3567
              protocol: TCP
      restartPolicy: Always
